### ISSUE TITLE
编译qemu

### ISSUE THREAD

**Issue by zhuifengwfy** [c-sky/forum#22]
你好，我从git上下载了qemu：https://github.com/c-sky/qemu.git
请问如何编译和运行呢，kernel编译编译为sc8925_defconfig

**Comment by guoren83** [comment]
单独编译，参考这里：
https://github.com/c-sky/buildroot/blob/master/package/csky-qemu/csky-qemu.mk

直接用buildroot，它会自动编译csky-qemu，参考：
https://github.com/c-sky/buildroot/blob/master/board/qemu/csky/readme.txt
