### ISSUE TITLE
4MB SPI-FLASH更新啦，改善了按键响应

### ISSUE THREAD

**Issue by guoren83** [c-sky/forum#29]
目前的播放器，GPIO按键有点卡，新固件已经改善，亲测效果显著：
[https://github.com/c-sky/tools/tree/master/gx6605s](https://github.com/c-sky/tools/tree/master/gx6605s)

**Comment by ljbfly** [comment]
![image](https://user-images.githubusercontent.com/24551741/33320985-ef1f8c64-d47e-11e7-8bd4-2c308742e4f7.png)

**Comment by guoren83** [comment]
参数错了吧

**Comment by guoren83** [comment]
boot.elf -b gx6605s-6605s-sflash.boot -d /dev/ttyUSB0 -c serialdown 0 loader-sflash.bin
我readme serialdown漏写了 0
sorry

**Comment by guoren83** [comment]
readme 已经更正，谢谢

**Comment by ljbfly** [comment]
gx6605s-6605s-sflash.boot 这也不对
刷完之后，好像不能启动u盘的镜像了

**Comment by guoren83** [comment]
是的 sorry ...

**Comment by guoren83** [comment]
你可以先还原到之前的版本，那个有版本记录

**Comment by guoren83** [comment]
选择最早的版本

**Comment by guoren83** [comment]
https://github.com/c-sky/tools/commit/508f0dbb239f95de214fef9d53f8b0297cd743b0#diff-bed56d35e582b82d8c301dc928246be0

**Comment by guoren83** [comment]
已经修正，谢谢 ljbfly
