### ISSUE TITLE
Windows 串口驱动

### ISSUE THREAD

**Issue by ruier** [c-sky/forum#31]
你好 @guoren83  我启动了板子中的默认镜像，但是插上 win 10 PC，没有任何反应，串口无法使用，请问怎样才能在 Windows 下使用串口

**Comment by ljbfly** [comment]
插上看看设备管理器里识别的串口，串口助手打开就行了115200,n,8,1

**Comment by ruier** [comment]
必须用原装的 usb 线，我用我手机的不行，友情提醒，买根官方的原装 usb 线，不然找不到设备

**Comment by guoren83** [comment]
windows 驱动，这个我们用的是 ch340g 串口芯片，这个是淘宝上广泛使用的，来自南京芯恒，你可以到他们官方网站上找找 windows 驱动：
http://www.wch.cn

其实是简单 micro-usb 线， 5V DP DB GND 四根，但是电源有点要求，要能承受 1A-2A
质量太差的 micro-usb 可能存在供电问题，还有些micro-usb 线 把 DP DB 省略了。你可以看我们的原理图，很简单，就4根线。

https://github.com/c-sky/tools/raw/master/gx6605s/pcbv1.1.pdf
