### ISSUE TITLE
为 c-sky 编译程序

### ISSUE THREAD

**Issue by wuhanstudio** [c-sky/forum#32]
请问交叉编译 c-sky-linux 的可执行程序，需要用 c-sky/gcc 和 c-sky/uclibc-ng 吗？ 因为现在系统没有太多可用的程序。

请问有相关的介绍吗？

顺便一提，如果能有可用 IO，SPI，I2C引出来就好了，现在只有 独立按键 和 led

**Comment by wuhanstudio** [comment]
找到了编译好的工具链：
https://github.com/c-sky/tools/blob/master/csky-linux-tools-x86_64-glibc-linux-4.9.56-20171205.tar.gz

**Comment by wuhanstudio** [comment]
buildroot 默认是 glibc

编译了 openssh, tmux, http-server, lua, pip 之后，这块板子相对于NanoPi, RasbPi, OrangePi, 有一些建议:

1. 硬件 : 这块板子有 jtag 调试很方便，但是外设相对其他 arm 板少了些。全靠USB，按键和LED，不过这毕竟也得看 SoC 本身有没有SPI, I2C 接口，现在只找到了CPU手册，不清楚 SoC 有提供哪些外设。

2. 软件 : 跑跑 Python, Lua, 搭个网站还可以，但是buildroot 建议默认开启交换空间支持，默认配置不能开交换空间 pip install 内存就不够了。毕竟这不是debian，软件包大部分需要交叉编译。

总体感觉这块板子特点在于有jtag，外设比较弱，软件包需要自己编译，价格和 OrangePi 差不多。

期待 19 元版本，价格就是亮点，却又失去了jtag(其实感觉不太需要jtag)。还是支持一下国产，但是确实还有很多不方便，外设，软件包，CPU发热，再次期待19元，那用作学习就是极好的。

**Comment by guoren83** [comment]
感谢你的反馈，目前这块板子还只是试水，大规模推广前，还有很多东西需要准备。感谢超级用户们在产品初期对我们的支持，和反馈。

**Comment by xuefengedu** [comment]
@wuhanstudio hello, do you know how to build packages like openssh, tmux, http-server, lua, pip? can yo u share me? thanks very much!

**Comment by wuhanstudio** [comment]
> @wuhanstudio hello, do you know how to build packages like openssh, tmux, http-server, lua, pip? can yo u share me? thanks very much!

1. The easiest way is to use buildroot, you may reference [here]( https://c-sky.github.io/docs/quick-compile.html), use `make menuconfig` to add packages (openssh, tmux, http-server, lua, pip all available).

2. An alternative would be compiling from source code with [toolchain](https://github.com/c-sky/tools/) if those pacakges you'd like to add is not provided by buildroot while this rarely happens.

**Comment by xuefengedu** [comment]
@wuhanstudio nice! great! thanks for help!
