### ISSUE TITLE
编译时报错

### ISSUE THREAD

**Issue by muyongming** [c-sky/forum#52]
/../gcc/config/gnu-user.h:36:0: note: this is the location of the previous definition
 #define ASM_APP_OFF "#NO_APP\n"
 
Makefile:1085: recipe for target 'ubsan.o' failed
make[2]: *** [ubsan.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/mu/gx6605s/buildroot/output/build/host-gcc-initial-d985fbfeb69dd3b80f0c0276013ccbeaaa6d7e0d/build/gcc'
Makefile:4113: recipe for target 'all-gcc' failed
make[1]: *** [all-gcc] Error 2
make[1]: Leaving directory '/home/mu/gx6605s/buildroot/output/build/host-gcc-initial-d985fbfeb69dd3b80f0c0276013ccbeaaa6d7e0d/build'
package/pkg-generic.mk:248: recipe for target '/home/mu/gx6605s/buildroot/output/build/host-gcc-initial-d985fbfeb69dd3b80f0c0276013ccbeaaa6d7e0d/.stamp_built' failed
make: *** [/home/mu/gx6605s/buildroot/output/build/host-gcc-initial-d985fbfeb69dd3b80f0c0276013ccbeaaa6d7e0d/.stamp_built] Error 2
➜  buildroot git:(master)

**Comment by muyongming** [comment]
把
 if (xloc.file == NULL || strncmp (xloc.file, "\1", 2) == 0 || xloc.file == **’\0‘** || xloc.file[0] == "\xff"s
修改为：
 if (xloc.file == NULL || strncmp (xloc.file, "\1", 2) == 0 || xloc.file == **”\0“** || xloc.file[0] == "\xff"s
该处报错消失

**_# 这么改没问题吧？_**

**Comment by guoren83** [comment]
gcc/ubsan.c 这是gcc 的公共文件，非arch相关。
建议还是在 ubuntu 16.04  apt-get install build-enssitial 环境编译
