### ISSUE TITLE
请问这个芯片零售渠道能买到吗？

### ISSUE THREAD

**Issue by ahfong2006** [c-sky/forum#58]
对不起标题里没写详细，我指的是GX6605S

**Comment by ahfong2006** [comment]
另外看到你们另外一块IOT开发版，使用的芯片CH2201，这个购买渠道，大致价位可以透露下吗？

**Comment by guoren83** [comment]
这个要问杭州国芯了

**Comment by guoren83** [comment]
`另外看到你们另外一块IOT开发版，使用的芯片CH2201，这个购买渠道，大致价位可以透露下吗？`

不清楚，这里只讨论 csky-linux
