### ISSUE TITLE
使用 User GPIO 访问 I2C 设备

### ISSUE THREAD

**Issue by wuhanstudio** [c-sky/forum#60]
您好，我注意到 User GPIOs 里面 PORT14 和 PORT15 实际上是 I2C 总线的 SDA 和 SCL。

![screenshot at 2018-08-27 09-00-55](https://user-images.githubusercontent.com/15157070/44635425-e895e300-a9d7-11e8-932d-647814f9fe44.png)

![screenshot at 2018-08-27 09-00-23](https://user-images.githubusercontent.com/15157070/44635420-df0c7b00-a9d7-11e8-8cf7-e0801deaa70f.png)

但是我在 linux 下没有看到相应的设备。

`# modprobe i2c-dev`
`# ls /dev/i2c*`
`No such file or directory`

-------

我想到了2种可能：

1. Kernel: 我看了一下 buildroot 里 kernel 的配置，其实是打开了 I2C 设备支持的。

    ` make ARCH=csky menuconfig`

    ![screenshot at 2018-08-27 09-10-31](https://user-images.githubusercontent.com/15157070/44635579-162f5c00-a9d9-11e8-9754-43dd7aadf942.png)

2. 设备树: 设备树文件里没有声明 I2C 设备，如果我要将 PORT14 和 PORT15 作为 I2C 使用，请问设备树文件应该怎么修改呢，是不是还需要修改其他的文件呢？ 

    [https://github.com/c-sky/csky-linux/blob/master/arch/csky/boot/dts/gx6605s.dts](https://github.com/c-sky/csky-linux/blob/master/arch/csky/boot/dts/gx6605s.dts)

------

因为我最近把单色液晶屏的驱动移植到了 arm linux 平台，如果 c-sky 成功打开了 I2C 设备，那就也能在 c-sky 上使用各种显示屏了。

[https://github.com/olikraus/u8g2/wiki/gallery#2-feb-2018--hx1230-96x68](https://github.com/olikraus/u8g2/wiki/gallery#2-feb-2018--hx1230-96x68)

**Comment by guoren83** [comment]
gx6605s 没有开放 i2c 驱动 ... sorry

**Comment by wuhanstudio** [comment]
谢谢您的回复，
那看样子暂时不能使用I2C了，修改设备树需要知道 gx6605s 芯片 i2c 的内存地址。
不过也可以理解，毕竟 gx6605s 主要是智能电视机顶盒，没有公开的SoC手册，确实和全志H3，H5这样的SoC需求不同。

**Comment by wuhanstudio** [comment]
我之后想了一下，可以用 GPIO 模拟 I2C，终于在 c-sky 上成功运行了。

> 项目地址：[https://github.com/wuhanstudio/u8g2-arm-linux](https://github.com/wuhanstudio/u8g2-arm-linux)

在 linux kernel 里已经有 I2C Bit Bang 的驱动了，打开选项并修改设备树之后，就可以利用 PIN14 和 PIN15 模拟 I2C 总线了。

这样，这块开发板就可以连接很多 I2C 外设了，比如温湿度传感器，显示屏，陀螺仪 ...

<img alt="csky-u8g2" src="https://raw.githubusercontent.com/wuhanstudio/u8g2-arm-linux/master/img/csky-ck610.jpg" width="400" />

**Comment by wuhanstudio** [comment]
我觉得可以是不是可以把 [ 打开 I2C 总线 ] 添加到 buildroot 的配置里，这样这块开发板默认闲置的两个排针引脚就可以用作I2C总线，连接各种外设了。

[ 1 ] Kernel 配置

    --> Device Drivers
        --> I2C Support
            <*> I2C device interface
            I2C Hardware Bus support  --->
                <*> GPIO-based bitbanging I2C

[ 2 ] 设备树

    #include <dt-bindings/gpio/gpio.h>
    i2c@0 {
        compatible = "i2c-gpio";
        sda-gpios = <&gpio0 14 (GPIO_ACTIVE_HIGH|GPIO_OPEN_DRAIN)>;
        scl-gpios = <&gpio0 15 (GPIO_ACTIVE_HIGH|GPIO_OPEN_DRAIN)>;
        i2c-gpio,delay-us = <2>;        /* ~100 kHz */
        #address-cells = <1>;
        #size-cells = <0>;
    };

当然 PORT14，PORT15，PORT20 也可以作为 SPI 总线使用：

[ 1 ] Kernel 配置

    --> Device Drivers
        --> SPI Support
                <*> GPIO-based bitbanging SPI Master

[ 2 ] 设备树

    spi {
            compatible = "spi-gpio";
            #address-cells = <0x1>;
            ranges;
            gpio-sck = <&gpio 20 0>;
            gpio-miso = <&gpio 14 0>;
            gpio-mosi = <&gpio 15 0>;
            cs-gpios = <&gpio 10 0>;
            num-chipselects = <1>;

                /* clients */
    };

不过只有三个排针，所以把 CS 随意设置为 gpio10，手动把外设的 CS 接地就可以了。

**Comment by guoren83** [comment]
太牛了，一定要加上，非常感谢，而且也在 https://github.com/wuhanstudio/u8g2-arm-linux
看到你的demo 照片了，非常棒。

**Comment by ahfong2006** [comment]
不错，好歹I2C也算能用了。
