### ISSUE TITLE
来这里确认一下，是不是芯片的datasheet没有开放？

### ISSUE THREAD

**Issue by mangobuge** [c-sky/forum#61]
来这里确认一下，是不是芯片的datasheet没有开放？

**Comment by wuhanstudio** [comment]
CPU CK610 手册: 
    
    https://github.com/c-sky/tools/raw/master/gx6605s/CK610_spec.pdf

SoC GX6605S 确实没有

**Comment by MangoNoFlake** [comment]
好的，了解了
