### ISSUE TITLE
默认配置文件改变 csky_gx6605s_br_defconfig

### ISSUE THREAD

**Issue by wuhanstudio** [c-sky/forum#64]
以前 buildroot 默认配置是
csky_gx6605s_defconfig
sky_gx6605s_fbcon_defconfig

但是最近发现默认配置变了，
csky_gx6605s_fbcon_br_defconfig
csky_gx6605s_br_defconfig

请问添加的 br 是代表什么呢？

**Comment by mardteabk201** [comment]
br代表buildroot

**Comment by wuhanstudio** [comment]
> br代表buildroot

谢谢，原来这么直白，我还以为有特殊的含义 ;) 代表新功能。
