### ISSUE TITLE
两个关于接口的问题

### ISSUE THREAD

**Issue by zyppe** [c-sky/forum#71]
如果飞线把GPIO端口引出来，GPIO能用吗？
能否推荐下这个板子的JTAG线？

**Comment by zyppe** [comment]
还有一个，能在文档里面多解释下怎么用串口使用这个开发板嘛？

**Comment by guoren83** [comment]
> 如果飞线把GPIO端口引出来，GPIO能用吗？
> 能否推荐下这个板子的JTAG线？

有端口复用问题，pin-mux 驱动还没弄好



> 还有一个，能在文档里面多解释下怎么用串口使用这个开发板嘛？

应该有的，在 buildroot/board/nationalchip/readme.txt

**Comment by zyppe** [comment]
1.见过有人吐槽的就是这个板子没有GPIO，但是这个板子的线相对较粗，所以GPIO如果有官方的方案会很好的。
2.JTAG和串口很多人是第一次在Linux开发板上面接触（大部分都是用树莓派，香橙派之类的，一般都是用SSH，或者干脆用GUI），所以需要更多的解释（比如一个非常“弱智”的问题，串口能传文件吗？）。

**Comment by guoren83** [comment]
> 1.见过有人吐槽的就是这个板子没有GPIO，但是这个板子的线相对较粗，所以GPIO如果有官方的方案会很好的。
> 2.JTAG和串口很多人是第一次在Linux开发板上面接触（大部分都是用树莓派，香橙派之类的，一般都是用SSH，或者干脆用GUI），所以需要更多的解释（比如一个非常“弱智”的问题，串口能传文件吗？）。

1. GPIO 是有的，不多，你可以看 demo 的 dts ，pcb 的号码和 dts 里是对得上的，直接可以用。
2. 串口是用来做终端的，终端类的文件传输工具都可以用，比如 rz

**Comment by aisk** [comment]
@guoren83 求教，有办法使用串口直接访问 Linux 下的 shell 终端吗？
