### ISSUE TITLE
how to install package in gx6605 c-sky board?

### ISSUE THREAD

**Issue by xuefengedu** [c-sky/forum#75]
Hello, thanks for help in advance!
how to install package in gx6605 c-sky board?

do we have built any packages for gx6605 c-sky board? where location or URL?

how to install them? `pacman` like official arch? or `aurman`?

If no package, how to build the packages ? any document?
I see many tool chain files under https://github.com/c-sky/tools, how to use them?

**Comment by aisk** [comment]
There is no package manager for buildroot, but you can build some packages from source when build the system image, see: https://aisk.github.io/posts/build-csky-gx6605s.html
