### ISSUE TITLE
how to connect internet to gx6605s?

### ISSUE THREAD

**Issue by g2ragrawal** [c-sky/forum#98]
i have bought vingajoy premium hd setup-box. which have cpu gx6605s and on box its mentioned that wifi through usb port but how to connect? i have tried using smartphone via usb tetharing but it didn't work.

**Comment by sandeep251188** [comment]
> i have bought vingajoy premium hd setup-box. which have cpu gx6605s and on box its mentioned that wifi through usb port but how to connect? i have tried using smartphone via usb tetharing but it didn't work.

using a wifi adapter...u can connect to network
